version: 2.1
jobs:
  build:
    docker:
      - image: shailygupta/converge:v2
        environment:
          APP_ENV: test
    steps:
      - run:
          name: Find branch name
          command: ./scripts/converge.sh