version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu
        environment:
          APP_ENV: test
    steps:
      - run:
          name: Download git
          command: apt install -y git && git --version
      - run:
          name: Clone the repo
          command: git clone https://github.com/shailygup/circle-ci.git; cd circle-ci
      - checkout
      - run:
          name: Find branch name
          command: ./scripts/converge.sh