version: 2
jobs:
  build:
    docker:
      - image: python:3
        environment:
          APP_ENV: test
    steps:
      - checkout
      - run:
          name: Signalfx converge
          command: echo "Hi"
