version: 2.1
jobs:
  build:
    docker:
      - image: python:3
        environment:
          APP_ENV: test
    steps:
      - run:
          name: Find files updated
          command: > 
                if [[ ! -z "$CIRCLE_BRANCH" && "$CIRCLE_BRANCH" != "master" ]]; then \
                git checkout -q master && git reset  -q --soft origin/master && git checkout -q $CIRCLE_BRANCH \
                  if ! (git --no-pager diff --name-only master | grep metadata.rb > /dev/null); then \
                    echo "It seems like you forgot to update the version number in metadata.rb!" \
                    exit 1 \
                  fi \
                fi
