version: 2.1
jobs:
  git_pull:
    steps:
      - checkout
      - run:
          name: Git Pull from Master
          command: git pull origin master
  build:
    docker:
      - image: shailygupta/converge:v2
        environment:
          APP_ENV: test
    steps:
      - checkout 
      - run:
          name: SignalFx Converge
          command: ./scripts/converge.sh
  