version: 2.1
jobs:
  build:
    docker:
      - image: python:3
        environment:
          APP_ENV: test
    steps:
      - run:
          name: Find files updated
          command: if [[ ! -z "$CIRCLE_BRANCH" && "$CIRCLE_BRANCH" != "master" ]]; then
                git checkout -q master && git reset  -q --soft origin/master && git checkout -q $CIRCLE_BRANCH
                fi
