version: 2.1
jobs:
  build:
    docker:
      - image: python:3
        environment:
          APP_ENV: test
    steps:
      - run:
          name: Find branch name
          command: |
              echo $CIRCLE_BRANCH