version: 2.1
jobs:
  build:
    docker:
      - image: shailygupta/converge:v2
        environment:
          APP_ENV: test
    steps:
      - run:
          name: Find branch name
          command: |
              echo $CIRCLE_BRANCH
              cd /app/circle-ci
              if [[ ! -z "$CIRCLE_BRANCH" && "$CIRCLE_BRANCH" != "master" ]]; then git checkout -q master && git reset  -q --soft origin/master && git checkout -q ${CIRCLE_BRANCH} && git --no-pager diff --name-only master ; fi