version: 2.1
jobs:
  build:
    docker:
      - image: python:3
        environment:
          APP_ENV: test
    steps:
      - run:
          name: Find files updated
          command: |
                echo ${$CIRCLE_BRANCH}
