version: 2.1
jobs:
  build:
    docker:
      - image: debian:stable-slim
        environment:
          APP_ENV: test
    steps:
      - checkout
      - run:
          name: Find branch name
          command: ./scripts/converge.sh